### PR TITLE
Deprecate proxy-query `zerovm_sysimage_devices` config param

### PR DESCRIPTION
**Pull request by larsbutler**
The `object-query` and `proxy-query` configurations both have a `zerovm_sysimage_devices` parameter. However, they are treated differently. (But the docs indicated that they are the same!)
- `object-query` requires a list of `image-name` and `path-to-file` values
- `proxy-query` requires a list of `image-name` values
  - We only have `image-name` parameters here, because the actual image files are not installed on the proxy nodes (they are only installed on the object nodes)

Clearly these are different things. So in the proxy configuration, this parameter has been renamed to the more accurate `zerovm_sysimage_device_names`.

This patch fixes all of that, including vagrant scripts and docs.

Let me know if I missed something.

### CODE REVIEW

**Comment by pkit** [comment]
Dunno why you think that " proxy-query requires a list of image-name values " :)
It was the way you describe earlier, but was altered to have the same syntax.
If it does not have the same syntax then it's a bug, but I think it works. :)
Yes proxy-query nodes have no images installed at the path, but for the sake of simpler config I have decided to use exactly the same format in both cases.

**Comment by larsbutler** [comment]
@pkit Technically, the current code does work. If you put `zerovm_sysimage_devices = python.2.7 /foo/bar` in the proxy config, the middleware will interpret this as two images: `python2.7` and `/foo/bar`. According to @rpedde, the proxy only has these names to validate system images referenced in jobs (or something like that). So technically it does work, because it has the valid image (`python2.7`) but it also has garbage (`/foo/bar`).

I dropped into a debugger at this point in the code (see https://github.com/zerovm/zerocloud/blob/a7cea84500362b873528c0b8ce5972390d9c9ff1/zerocloud/proxyquery.py#L471-474) and this indeed what happens. It works, but it's still a bug. =)

**Comment by pkit** [comment]
That's bad, because it should not happen, I do remember copying exactly the same code for handling this parameter from objectquery to proxyquery, how it ended up with something older is an interesting question.
I suppose it should be declared in zerocloud/common.py and then both constructors should use the same function.

**Comment by larsbutler** [comment]
Well, the code is similar but it's not the same. Compare the simplified versions:
- Used for object-query: https://github.com/larsbutler/zerocloud/commit/47f37eb28753e1ab095f297d308869739ae79f18
- Used for proxy-query: https://github.com/larsbutler/zerocloud/commit/383e56b79c0b651b714156105ae6dca2a730190a
- The first reads the config list, 2 by 2, and constructs a dict from the pairs.
- The second reads the config list and constructs a dict using each item in the list as a key. Values are always `None`.

**Comment by mgeisler** [comment]
As I understand it, the documentation promised that

```
zerovm_sysimage_devices =
    foo /path/to/foo.tar
    bar /path/to/bar.tar
```

should work on both the proxy server and the object server. On the proxy server the paths should have been ignored, but they are really turned into extra system images.

If that is true, then the right thing to do would be to fix the code so that the paths are no longer ignored. No deprecation necessary, only a bugfix.

**Comment by larsbutler** [comment]
> If that is true, then the right thing to do would be to fix the code so that the paths are no longer ignored.

These images don't actually exist on the proxy nodes. So it doesn't make sense to have the paths there; hence the variable is semantically different, hence the renaming and deprecation. @rpedde Can you confirm this?

**Comment by pkit** [comment]
> No change necessary for deployments that don't somehow rely on the behavior of this bug -- if they do, we don't have to care since the behavior wasn't documented.

+1 here

**Comment by larsbutler** [comment]
@rpedde originally suggested that we deprecate this. Ron, can you please share your thoughts on this?

**Comment by rpedde** [comment]
I think there are two ways to go:
1.  Make the behavior consistant across both proxy and object, leave the config value with the same name
2.  Make the behavior inconsistent across both proxy and object, change the name.

I'd vote for 1, but it doesn't make a ton of sense on the proxy server to specify paths to things that don't exist.  It makes people wrongly thing the images must be present on the proxy.  So if the names are the only things that are important, those should be the only things specified.  A config item that requires a tuples of (name, path) where the path is something arbitrary and unused should probably not require a path. 

This is my thinking anyway, but I could go either way on that.  If we had a bunch of users that would be inconvenienced by a config value change, I'd be less willing to pick 2, but as it stands, I could go either way on this, although I lean towards 2.

But do what thou wilt.

 -- Ron

**Comment by mgeisler** [comment]
> If we had a bunch of users that would be inconvenienced by a config value change, I'd be less willing to pick 2, but as it stands, I could go either way on this, although I lean towards 2.

Either way, we should not inconvenience anybody. We've talked about this some times: we won't break backwards compatibility for our users. That's an important mindset to stick to if you want to build respectable software. (As a consequence of this, I'm very unimpressed when a project proudly declares that they'll use _semantic versioning_ and thus periodically take the liberty of not caring about backwards compatibility.)

Given that commitment to backwards compatibility, I think it is much easier for us and less confusing for the users if you just fix the code to do what the documentation has said it does all along. That way we won't have to deal with maintaining backwards compatibility between the two config keys.

**Comment by pkit** [comment]
I've looked at it very carefully and it looks like proxy middleware needs system_images list only to do a sanity check on daemon configs (there are some other even less important sanity checks that use it, that can be easily removed).
On the other hand we can probably make better checks by actually trying to validate daemons on proxy startup and using the result of that as an indicator. I think it's a much cleaner way of dealing with that issue.

**Comment by mgeisler** [comment]
> On the other hand we can probably make better checks by actually trying to validate daemons on proxy startup and using the result of that as an indicator. I think it's a much cleaner way of dealing with that issue.

I'm unsure what this means? Are you saying that we can remove the system images from the proxy configuration?

**Comment by pkit** [comment]
Yes, we can remove system images from proxyquery. I hope so, at least. :)

**Pull request closed without merging**
