### PR TITLE
fix empty stdin from request

### PR DESCRIPTION
**Pull request by pkit**
in some requests the stdin channel can be attached to request data
if the request data is empty the channel local path was unpopulated which lead to HTTP 400
this patch will populate the local path for `stdin` with `/dev/null` in such case (this is a standard behavior for CGI)
fixes issue #152

### CODE REVIEW

**Comment by pkit** [comment]
recheck please

**Comment by larsbutler** [comment]
retest this please

**Comment by larsbutler** [comment]
Cool, I'm testing this now.

**Comment by larsbutler** [comment]
Yep, it's fixed! Nice work. =)

**Pull request merged**
