### PR TITLE
Code cleanup

### PR DESCRIPTION
**Pull request by larsbutler**
This is the first of several patches to attempt to cleanup and clarify the ZeroCloud code. Test coverage is quite good, so this sort of refactoring should be easy to do with confidence.

### CODE REVIEW

**Comment by pkit** [comment]
load_server_conf was duplicated to remove dependency on zerocloud, because queue service may be extracted to different project in the future.
iter_pairs is a solution for non-existing problem :)
it can be emulated by `dict(zip(*[iter(list)]*2))` or `dict(zip(list[0::2], list[1::2]))`

**Comment by larsbutler** [comment]
> load_server_conf was duplicated to remove dependency on zerocloud, because queue service may be extracted to different project in the future.

I had no idea. Which project is that?

> ... it can be emulated by dict(zip(_[iter(list)]_2)) or dict(zip(list[0::2], list[1::2]))

I like the second one better.

**Comment by pkit** [comment]
> I had no idea. Which project is that?

I think that queue middleware can be useful without zerocloud. I even regret putting it in the current HEAD branch right now.

> I like the second one better.

Can be replaced with the second one. :)

**Comment by larsbutler** [comment]
> I think that queue middleware can be useful without zerocloud. I even regret putting it in the current HEAD branch right now.

Do we need the queue for job chaining? If so, then I think it makes sense to have it in HEAD.

> Can be replaced with the second one. :)

I replaced it.

**Comment by pkit** [comment]
> Do we need the queue for job chaining?

No, not needed.
Queue is needed for task manager/scheduler only, which is not implemented yet.

> I replaced it.

I still have problem with: 
- zc_common
- load_server_conf

I would also add another test case for the case of odd number of arguments in list, but I'm ok with adding it myself.

**Comment by larsbutler** [comment]
Okay, how does it look now?

**Comment by pkit** [comment]
+1

**Pull request merged**
