### PR TITLE
objectquery: simplify closing of file objects

### PR DESCRIPTION
**Pull request by larsbutler**
This takes advantage of the file context manager (`with`) to simplify
closure of files. This patch removes several explicit `fp.close()`
statements.

### CODE REVIEW

**Comment by larsbutler** [comment]
Oh, I don't know if you noticed, but I snuck something else in there. I changed the type of an exception:  the `json.load` should never throw anything else other than a `ValueError` (so catching `Exception` is a bit heavy-handed).

**Comment by larsbutler** [comment]
I forgot to include that in the commit message as well. I just know that @mgeisler is going to scold me for that someday. =)

**Comment by pkit** [comment]
That is ok, if you think that json and simplejson behave the same way

**Comment by larsbutler** [comment]
@pkit Good point. The built-in `json` package raises a `ValueError` (if you do something like `json.loads('')` or `json.loads('[')`. `simplejson` raises its own `JSONDecodeError`, but this exception inherits from `ValueError`, it's not a problem.

**Pull request merged**
