### PR TITLE
`zerovm_query` HTTP responses: bug fixes and clarification

### PR DESCRIPTION
**Pull request by larsbutler**
I was reading through the `zerovm_query` code, and I found a couple of things which might be bugs. The branch is a work in progress, and I need some feedback.

I've added inline comments to detail my questions. Please have a look.

### CODE REVIEW

**Comment by larsbutler** [comment]
@pkit Okay, thanks for the feedback. I've updated each commit accordingly.

**Comment by pkit** [comment]
@larsbutler sorry, but now looking at the 405 error case I cannot recommend 405 error there
Proxy -> object communication always uses POST, therefore logically the method is always allowed.

**Comment by larsbutler** [comment]
@pkit Okay, I'm confused now. If that's true, then the previous code would always throw a 400 if `container` evaluates to true and the request is not a GET. So that would mean that POSTs to a container would result in 400, and would effectively not be supported. Right?

**Comment by pkit** [comment]
@larsbutler access_type = GET has nothing to do with HTTP GET :)
And it cannot be converted to HTTP GET, because tar payload is transferred in both directions

**Comment by larsbutler** [comment]
@pkit Oh, I didn't realize that. The verbs like "PUT" and "GET" totally confused me.

 So, what's the difference between `access_type` and the HTTP verb? I see now (I missed it before) that it comes from the `x-zerovm-access` header. What does that mean?

**Comment by pkit** [comment]
@larsbutler proxy <-> object servers are using HTTP protocol. For Zerocloud we must send data proxy -> object and object -> proxy, which can be supported _unfortunately_ only by POST, there is no other verb. But, some queries access Swift objects in read-only fashion, and other - in write only.
Read-only - you attach zerovm to object and process it, sending result back (access_type = GET).
Write-only - you attach zerovm to object and write it as a new object, sending result back (access_type = PUT).

**Comment by larsbutler** [comment]
@pkit Okay, I submitted a new version. If the request is on a container, GET and POST are supported (although I don't yet see a case for a POST in `zerovm_query`). If it's not a GET or POST, a 405 is returned. Is this correct now?

**Comment by pkit** [comment]
@larsbutler access_type can be only GET or PUT. Nothing else.

**Comment by larsbutler** [comment]
@pkit Is `PUT` allowed on a container? I don't see any cases for this in the code.

**Comment by pkit** [comment]
"PUT" is not allowed for container only "GET", which can be possibly exchanged for "WRITE" and "READ", respectively, to avoid confusion.

**Pull request merged**
