### PR TITLE
Debug logging for `zerovm_query`

### PR DESCRIPTION
**Pull request by larsbutler**
Partially addresses https://github.com/zerovm/zerocloud/issues/106.

This change add debug logging output for all of the HTTP responses returned by `zerovm_query`. This includes a change to the way the responses are propagated. Instead of `return` statements, HTTP response can be raised as exceptions. This helps in a couple of ways:
1. We can differentiate "normal" or "successful" responses from error conditions.
2. We can do slightly different logging depending on the case. In the successful case, it's not really necessary to log the response body: with the current implementation, there is no body. In the error cases, the body includes a helpful message explaining the problem, so that's good to have in the logs.
3. This allows us to be more flexible in refactoring `zerovm_query`. I find this large method difficult to reason about in its entirety, and I would like to break it up into a handful of smaller methods.

### CODE REVIEW

**Comment by pkit** [comment]
@larsbutler looks good to me, but I think you can use HTTPException dance inside ProxyObjectQuery __call__() method, this way there is no need to do yet another function call.

**Comment by pkit** [comment]
@larsbutler see: https://github.com/zerovm/zerocloud/blob/swift-2.0/zerocloud/proxyquery.py#L576

**Comment by larsbutler** [comment]
@pkit Hmmm, that would be nice, but I think it would break a lot of tests which exercise `zerovm_query` directly.

**Comment by pkit** [comment]
@larsbutler I think we need to rewrite them to use get_response() which is pretty similar in behaviour.
And in fact I just forgot to do that (some tests do use get_response)

**Comment by larsbutler** [comment]
I like the idea of being more consistent with the HTTP response handling (exceptions vs. return values). Can I do that in a follow-up patch? I think it's getting slightly out of scope for this one.

**Comment by pkit** [comment]
I just don't like propagating indirections. But I think we can do it in separate patch.
Will continue reviewing.

**Comment by larsbutler** [comment]
What do you mean by "propagating indirections"? Do you not like the exception-raising approach?

**Comment by pkit** [comment]
I do not like:
func1() -> call func2() -> call func3() -> ....
if it's not absolutely needed.

**Comment by larsbutler** [comment]
Ah okay. Well, in that case you might not like my suggestion for subsequent patches. =) I want to break up `zerovm_query` into smaller, separate methods so the code is easier to understand and modify.

**Comment by pkit** [comment]
@larsbutler It depends on the level of "smallness".
I think that small methods are not more readable than big ones just by virtue of being small

**Comment by larsbutler** [comment]
What I had in mind (which I don't know is feasible) is something like this:

I want to logically group various conditions. For example, I would like to be able to group cases where a "Bad Request" is returned, or another common response type. Another type of grouping would be requests on objects vs. containers. Stuff like that. For me, this kind of grouping is partially about being able to find things easily, but also about being able to _ignore_ things I don't care about when I'm looking for something specific.

**Comment by pkit** [comment]
I have no problem with refactoring, But I will be against changes that do not introduce better readability and new functionality (both obviously from my point of view only). :)

**Comment by larsbutler** [comment]
Fair enough. :) I will try to keep that in mind. Hopefully we can find a nice common ground between our preferred styles.

**Pull request merged**
