### PR TITLE
Flake8 cleanups and add tox config

### PR DESCRIPTION
**Pull request by mgeisler**
Jenkins is setup to test this on new pull requests.

### CODE REVIEW

**Comment by mgeisler** [comment]
Hmm, something is wrong in Jenkins... let me investigate

**Comment by mgeisler** [comment]
retest this please

**Comment by mgeisler** [comment]
retest this please

**Comment by pkit** [comment]
NodeEncoder and mem_etag are needed for some future functionality
need to ignore these errors and leave it be...

**Comment by pkit** [comment]
shared_containers need to be deleted, will do it shortly

**Comment by pkit** [comment]
let's re-frame this one into several pull requests, and then I will merge it
1. All tarstream fixes (can be merged without a problem, ironically tarstream code is taken from core python tar module, looks like PEP8 did not exist then...)
2. Other small stuff like newlines
All other fixes need to be discussed, I suppose.

**Pull request merged**
