### PR TITLE
rework account home to support globbing patterns

### PR DESCRIPTION
**Pull request by pkit**
rework and fix behavior of c567b1012b80cbd23d2aeeb7b71e018ac99b948f
- now supports `.` (dot) or `~` (tilde) as a current account in Swift URLs
- now the expansion happens earlier and the globbing patterns work with it, i.e. `swift://~/c/obj*` will be correctly handled

### CODE REVIEW

**Comment by willkelly** [comment]
there are some issues with jenkins not making venvs.  constantine manually ran tests.

**Comment by mgeisler** [comment]
@willkelly I don't see any tests for this — I think it is okay if you ask @pkit for tests in a pull request like this. When you review a pull request, you automatically become the one who needs to remind the contributor to write good and tested code :-)

**Comment by mgeisler** [comment]
So, it seems that the [ShiningPanda plugin](https://www.shiningpanda-ci.com/docs/) we're using with Jenkins isn't shining as well as it should. It claims to make it easy to work with virtual environments in Jenkins, but it seems buggy somehow. It already has problems creating a working `tox` installation due to something weird with setuptools.

I think I'll try converting the job into a normal job where we use `virtualenv` directly.

**Comment by mgeisler** [comment]
retest this please

**Comment by pkit** [comment]
There are old tests for "home" expansion and they do pass.
You're right that there are no specific test for expansion and globbing together.
Maybe should be added. :)

**Comment by mgeisler** [comment]
Yeah, that would be super cool :-) Just so we have a little bit of hope that the feature doesn't break without us noticing in the future.

**Comment by mgeisler** [comment]
Updating the job seems to have worked.

**Pull request merged**
